branch-defaults:
  default:
    environment: fuji-dev
    group_suffix: null
global:
  application_name: fuji
  branch: null
  default_ec2_keyname: aws-eb_fuji
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: fuji
  repository: null
  sc: null
  workspace_type: Application
