# Generated by Django 2.0.2 on 2018-04-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuji', '0002_auto_20180207_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('endreco', models.CharField(max_length=400, unique=True)),
                ('email_contato', models.EmailField(max_length=60, unique=True)),
                ('nome_contato', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('endreco', models.CharField(max_length=200, unique=True)),
                ('email_contato', models.EmailField(max_length=60, unique=True)),
                ('nome_contato', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=3, unique=True)),
                ('descricao', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_emb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
