# Generated by Django 2.0.2 on 2018-04-03 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuji', '0003_customer_fornecedor_moeda_prioridade_termo_tipo_emb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('date_sent_vendor', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('proforma', models.CharField(blank=True, max_length=30, null=True)),
                ('invoice', models.CharField(blank=True, max_length=30, null=True)),
                ('intrucoes', models.CharField(blank=True, max_length=30, null=True)),
                ('embarcado_finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('awb', models.CharField(blank=True, max_length=30, null=True)),
                ('tracking', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_total', models.DecimalField(decimal_places=0, max_digits=16)),
                ('vencimento', models.DateTimeField(blank=True, null=True)),
                ('pago', models.NullBooleanField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('prioridade', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fuji.Customer')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fuji.Fornecedor')),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fuji.Moeda')),
                ('responsavel_fdb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('termo_pagto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fuji.Termo')),
                ('tipo_embarque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fuji.Tipo_emb')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
