# Generated by Django 2.0.2 on 2018-04-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuji', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prioridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fuji.Prioridade'),
        ),
    ]
