# Generated by Django 2.0.2 on 2018-04-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuji', '0005_auto_20180403_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='intrucoes',
        ),
        migrations.AddField(
            model_name='order',
            name='instrucoes',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Instruções de embarque'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fuji.Customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sent_vendor',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de envio ao fornecedor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='embarcado_finalizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Embarcado/Finalizado em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fuji.Fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='order',
            name='proforma',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Proforma Invoice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data recebida'),
        ),
    ]
