# Generated by Django 2.0.2 on 2018-04-03 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuji', '0006_auto_20180403_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_total',
            field=models.DecimalField(decimal_places=0, max_digits=16, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='awb',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='AWB'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Última atualização em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='moeda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fuji.Moeda', verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pago',
            field=models.NullBooleanField(verbose_name='Pago?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prioridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fuji.Prioridade', verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='order',
            name='responsavel_fdb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='order',
            name='termo_pagto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fuji.Termo', verbose_name='Termo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tipo_embarque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fuji.Tipo_emb', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tracking'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Última atualização por'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vencimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimento'),
        ),
    ]
