# Generated by Django 2.0.2 on 2018-04-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuji', '0007_auto_20180403_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sent_vendor',
            field=models.DateField(blank=True, null=True, verbose_name='Data de envio ao fornecedor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='embarcado_finalizado_em',
            field=models.DateField(blank=True, null=True, verbose_name='Embarcado/Finalizado em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_update',
            field=models.DateField(auto_now_add=True, verbose_name='Última atualização em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data recebida'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento'),
        ),
    ]
