# Generated by Django 2.0.2 on 2018-07-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuji', '0008_auto_20180406_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comentarios',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='finalidade',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='information',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='partName',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='partNamePort',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='remark',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
