# Generated by Django 2.0.2 on 2018-07-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuji', '0009_auto_20180712_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='designChange',
            new_name='designchange',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='partName',
            new_name='partname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='partNamePort',
            new_name='partnamePort',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='yenPrice',
            new_name='yenprice',
        ),
    ]
