# Generated by Django 2.0.2 on 2018-07-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuji', '0010_auto_20180712_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='partnamePort',
            new_name='partnameport',
        ),
    ]
